# Checks if a file has been committed under the .changes/unreleased directory
#
# Skip PRs labeled with 'dependencies'

on:
  pull_request:
    branches:
      - main
      - pre-release

name: Check if changelog entry exists

jobs:
  changelog_existence:
    name: Check if changelog entry exists
    if: "!contains(github.event.pull_request.labels.*.name, 'dependencies')"
    runs-on: ubuntu-latest

    steps:
      - name: Check if changelog file was added
        # https://github.com/marketplace/actions/paths-changes-filter
        # For each filter, it sets output variable named by the filter to the text:
        #  'true' - if any of changed files matches any of filter rules
        #  'false' - if none of changed files matches any of filter rules
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changelog_check
        with:
          filters: |
            exists:
              - '.changes/unreleased/**.yaml'

      - name: Fail job if changelog entry is missing and required
        if: steps.changelog_check.outputs.exists == 'false'
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: core.setFailed('Changelog entry required to merge.')
