name: Issue Comment Created Triage

permissions:
  issues: write
  pull-requests: write

on:
  issue_comment:
    types: [created]

jobs:
  issue_comment_triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # https://github.com/actions/checkout/releases/tag/v3.6.0
      - uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # https://github.com/actions-ecosystem/action-remove-labels/releases/tag/v1.3.0
        with:
          labels: |
            stale
            waiting-reply
