name: Closed Milestones

on:
  milestone:
    types: [closed]

permissions:
  issues: write
  pull-requests: write

jobs:
  Comment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: bflad/action-milestone-comment@ae6c9fdf5778064d4e09b4632604a16b7289096c  # TSCCR: no entry for repository "bflad/action-milestone-comment"
        with:
          body: |
            This functionality has been released in [${{ github.event.milestone.title }} of the language server](https://github.com/${{ github.repository }}/blob/${{ github.event.milestone.title }}/CHANGELOG.md).

            For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/${{ github.repository }}/issues/new/choose) following the template. Thank you!
